openapi: 3.0.0
info:
  title: supplierSite
  version: '1.0'
servers:
  - url: 'https://c2.tours'
paths:
  /subSupplier:
    post:
      summary: Create Supplier
      operationId: post-subSupplier
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  msg:
                    type: string
              examples:
                example-1:
                  value:
                    status: Success
                    msg: Solicitação enviado com sucesso
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                activites:
                  type: array
                  description: Array que recebe os tipos de atividades
                  items:
                    type: object
                    properties:
                      id:
                        type: number
                      name:
                        type: string
                    required:
                      - id
                      - name
                place:
                  type: string
                  description: Local da ativiadade
                socialMedia:
                  type: object
                  description: |
                    Recebe os tipos de redes sociais que a empresa possui e seus endereços
                  required:
                    - site
                    - instagram
                    - tripadvisor
                  properties:
                    site:
                      type: string
                      description: Recebe o Site da empresa
                    instagram:
                      type: string
                      description: Recebe o Instagram da empresa
                    tripadvisor:
                      type: string
                      description: Recebe o TripAdvisor da Empresa
                managingDdirector:
                  type: object
                  description: Recebe os dados do Diretor Geral
                  required:
                    - firstName
                    - lastName
                  properties:
                    firstName:
                      type: string
                      description: Primeiro Nome do Diretor Geral
                    lastName:
                      type: string
                      description: Sobrenome do Diretor Geral
                company:
                  type: object
                  description: Recebe dados da Empresa
                  required:
                    - nameCompany
                    - zipCode
                    - city
                    - address
                    - country
                    - currency
                  properties:
                    nameCompany:
                      type: string
                      description: Recebe o nome da Empresa
                    zipCode:
                      type: string
                      description: Recebe o CEP da empresa
                    city:
                      type: string
                      description: Recebe a Cidade da Empresa
                    address:
                      type: string
                      description: Recebe o endereço da Empresa
                    country:
                      type: string
                      description: Recebe o país da Empresa
                    currency:
                      type: string
                      description: Recebe a moeda da Empresa
                contact:
                  type: object
                  description: Recebe o contato da empresa
                  required:
                    - firstNameContact
                    - lastNameContact
                    - phoneNumberContact
                  properties:
                    firstNameContact:
                      type: string
                      description: Recebe o primeiro nome do contato da empresa
                    lastNameContact:
                      type: string
                      description: Recebe o sobrenome do contato da empresa
                    phoneNumberContact:
                      type: string
                      description: Recebe o telefone do contato da empresa
                login:
                  type: object
                  description: Recebe as informações de Login
                  required:
                    - email
                    - password
                  properties:
                    email:
                      type: string
                      description: Recebe o e-mail para Login
                    password:
                      type: string
                      description: Recebe a senha para Login
              required:
                - activites
                - place
                - socialMedia
                - managingDdirector
                - company
                - contact
                - login
            examples:
              example-1:
                value:
                  activites:
                    - id: 39
                      name: Ingressos para atrações
                  place: 'Rio de Janeiro, RJ, Brasil'
                  socialMedia:
                    site: 'https://www.ampercomunicacao.com.br'
                    instagram: '@ampercomunicacao'
                    tripadvisor: 'https://www.tripadvisor.com.br/Attraction_Review-g303506-d9555526-Reviews-C2Rio_Tours_Travel-Rio_de_Janeiro_State_of_Rio_de_Janeiro.html'
                  managingDdirector:
                    firstName: Richard
                    lastName: Salles
                  company:
                    nameCompany: Amper Comunicação
                    zipCode: '24020104'
                    city: Niterói
                    address: Rua José Clemente
                    country: Brasil
                    currency: Real Brasileiro
                  contact:
                    firstNameContact: Richard
                    lastNameContact: Salles
                    phoneNumberContact: '55999999999'
                  login:
                    email: richard@ampercomunicacao.com.br
                    password: amper
        description: ''
      parameters: []
      description: ''
    parameters: []
  /getSupplierReservations:
    get:
      summary: Get infos to suppliers dashboard
      tags:
        - suppliers
        - reservations
      responses:
        '200':
          description: OK
      operationId: get-getSupplierReservations
      description: Get infos to suppliers dashboard
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                AllSuppliersReservations:
                  type: array
                  description: 'Array de objetos contendo todas as reservas do fornecedor. Período: 30 dias antes da data atual até 5 dias após'
                  items:
                    type: object
                    properties:
                      tourName:
                        type: string
                        description: Nome do tour ao qual a reserva corresponde
                      tourDate:
                        type: string
                        description: Data do tour
                      tourHour:
                        type: string
                        description: Hora do tour
                      pax:
                        type: number
                        description: Quantidade de passageiros na reserva
                      passengerName:
                        type: string
                        description: Nome do passageiro responsável pela reserva
                      passengerTel:
                        type: string
                        description: Telefone do passageiro
                      totalPrice:
                        type: string
                        description: Valor total da reserva
                      status:
                        type: number
                        description: 1 para Check-in ou 0 para no-show
                    required:
                      - tourName
                      - tourDate
                      - tourHour
                      - pax
                      - totalPrice
                      - status
                tourReservations:
                  type: array
                  items:
                    type: object
                    description: Objeto com informações de reservas classificadas por tours
                    properties:
                      startDate:
                        type: string
                        description: Data de início do período ao qual as medidas se referem
                      endDate:
                        type: string
                        description: Data do fim do período ao qual as medidas se referem
                      tours:
                        type: array
                        description: Informações por tour
                        items:
                          type: object
                          properties:
                            tourName:
                              type: string
                              description: Nome do tour
                            tourCode:
                              type: string
                              description: Código do tour
                            tickets:
                              type: number
                              description: Número de tickets vendidos no período
                            pax:
                              type: number
                              description: 'Números de passageiros que adquiriram o ticket, considerando que cada ticket pode corresponder a mais de um passageiro'
                            grossValue:
                              type: number
                              description: Ganhos brutos com a venda de tickets deste tour neste período
                            netValue:
                              type: number
                              description: Ganhos líquidos com a venda de tickets deste tour neste período
                          required:
                            - tourName
                            - tourCode
                            - tickets
                            - pax
                            - grossValue
                            - netValue
                    required:
                      - startDate
                      - endDate
                      - tours
                invoincingSales:
                  type: array
                  description: Faturamento do fornecedor calculado por dia; retornaria apenas dias de um período de 60 dias.
                  items:
                    type: object
                    properties:
                      date:
                        type: string
                        description: Data do dia ao qual o faturamente corresponde
                      reservations:
                        type: number
                        description: Número de reservas
                      dayInvoincing:
                        type: number
                        description: Faturamento do dia
                    required:
                      - date
                      - reservations
                      - dayInvoincing
              required:
                - AllSuppliersReservations
                - tourReservations
                - invoincingSales
            examples:
              Exemplo de como é o objeto do gráfico:
                value:
                  data:
                    - labels:
                        - 28/04
                        - 29/04
                        - 30/04
                        - 01/05
                        - 02/05
                        - 03/05
                        - 04/05
                        - 05/05
                        - 06/05
                        - 07/05
                        - 08/05
                        - 09/05
                        - 10/05
                        - 11/05
                        - 12/05
                        - 13/05
                        - 14/05
                        - 15/05
                        - 16/05
                        - 17/05
                        - 18/05
                        - 19/05
                        - 20/05
                        - 21/05
                        - 22/05
                        - 23/05
                        - 24/05
                        - 25/05
                        - 26/05
                        - 27/05
                        - 28/05
                        - 29/05
                      datasets:
                        - label: Periodo anterior (Abr 2018 - Mai 2019)
                          lineTension: 0.1
                          backgroundColor: 'rgba(241, 91, 43, 0.15)'
                          borderColor: 'rgba(241, 91, 43, 1)'
                          pointRadius: 3
                          pointBackgroundColor: 'rgba(241, 91, 43, 1)'
                          pointBorderColor: 'rgba(241, 91, 43, 1)'
                          pointHoverRadius: 6
                          pointHoverBackgroundColor: 'rgba(241, 91, 43, 1)'
                          pointHoverBorderColor: 'rgba(241, 91, 43, 1)'
                          pointHitRadius: 10
                          pointBorderWidth: 2
                          data:
                            - 30000
                            - 1000
                            - 500
                            - 25000
                            - 1000
                            - 2000
                            - 30000
                            - 14000
                            - 2000
                            - 3000
                            - 12500
                            - 15000
                            - 11000
                            - 1900
                            - 15000
                            - 1000
                            - 2000
                            - 8000
                            - 14000
                            - 2000
                            - 3000
                            - 2500
                            - 8000
                            - 1000
                            - 500
                            - 11000
                            - 1000
                            - 2000
                            - 8000
                            - 14000
                            - 2000
                            - 10000
                        - label: Periodo atual (Abr 2018 - Mai 2019)
                          lineTension: 0.1
                          backgroundColor: 'rgba(78, 115, 223, 0.15)'
                          borderColor: 'rgba(78, 115, 223, 1)'
                          pointRadius: 3
                          pointBackgroundColor: 'rgba(78, 115, 223, 1)'
                          pointBorderColor: 'rgba(78, 115, 223, 1)'
                          pointHoverRadius: 6
                          pointHoverBackgroundColor: 'rgba(78, 115, 223, 1)'
                          pointHoverBorderColor: 'rgba(78, 115, 223, 1)'
                          pointHitRadius: 10
                          pointBorderWidth: 2
                          data:
                            - 0
                            - 10000
                            - 5000
                            - 15000
                            - 10000
                            - 20000
                            - 15000
                            - 25000
                            - 20000
                            - 30000
                            - 25000
                            - 40000
                            - 35000
                            - 25000
                            - 29000
                            - 32000
                            - 29000
                            - 30000
                            - 35000
                            - 35000
                            - 39000
                            - 42000
                            - 39000
                            - 34000
                            - 35000
                            - 35000
                            - 39000
                            - 42000
                            - 49000
                            - 44000
                            - 52000
                            - 59000
                            - 60000
              'Objeto de exemplo que estou usando em /main-dashboar (exceto pelo gráfico, que são os dados do outro exemplo)':
                value:
                  AllSuppliersReservations:
                    - tourName: Um dia no Rio
                      tourDate: '2020-06-12'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Isis Leal
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Meio dia no Rio
                      tourDate: '2020-06-12'
                      tourHour: '12:00'
                      pax: 2
                      passengerName: Richard
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Um dia em Búzios
                      tourDate: '2020-06-12'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: 'Santa Teresa, Lapa e Cinelândia'
                      tourDate: '2020-06-12'
                      tourHour: '10:00'
                      pax: 2
                      passengerName: Isis
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: um dia no rio
                      tourDate: '2020-06-12'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Isis Leal
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: um dia no rio
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Isis Leal
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Pão de Açucar com Ingresso
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Isis Leal
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: 'Rio: Corcovado, Cristo Redentor'
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Isis
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Angra dos Reis
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Richard
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-12'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-12'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-09'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-09'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-09'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-09'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-09'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-10'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-11'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                    - tourName: Ilha Grande Histórica
                      tourDate: '2020-06-13'
                      tourHour: '08:00'
                      pax: 2
                      passengerName: Rafael
                      passengerTel: '21999999999'
                      totalPrice: 300
                      status: 1
                  tourReservations:
                    startDate: '2020-06-03'
                    endDate: '2020-07-03'
                    tours:
                      - tourName: 'Rio: Corcovado, Cristo Redentor e praia de Copacabana'
                        tourCode: pqy2760
                        tickets: '100'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: Pão de Açucar com Ingresso e vista panoramica
                        tourCode: pqn8204
                        tickets: '100'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: Cristo Redentor
                        tourCode: p029383
                        tickets: '100'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: Um dia no Rio
                        tourCode: pqy2760
                        tickets: 300
                        pax: '100'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: 'Santa Teresa, Lapa e Cinelândia com Passeio de Bondinho e Escadaria Selarón'
                        tourCode: pq9ksa
                        tickets: '90'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: 'Passeio de Helicóptero & Voo Panorâmico - Rio de Janeiro'
                        tourCode: pqy2760
                        tickets: '10'
                        pax: '15'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: The Hidden Gem Across Rio de Janeiro
                        tourCode: pqy2760
                        tickets: '100'
                        pax: '120'
                        grossValue: '40000'
                        netValue: '20000'
                      - tourName: 'Christ the Redeemer, Sugar Loaf, Maracana and Selaron with Lunch'
                        tourCode: pqy2760
                        tickets: '100'
                        pax: '150'
                        grossValue: '50000'
                        netValue: '20000'
                      - tourName: Recebiveis de venda
                        tourCode: pqy2760
                        tickets: '100'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                      - tourName: 'Full Day in Rio: Christ the Redeemer, Sugar Loaf, Maracana and Selaron with Lunch'
                        tourCode: pqy2760
                        tickets: '100'
                        pax: '150'
                        grossValue: '30000'
                        netValue: '20000'
                  invoincingSales:
                    - date: '2020-06-03'
                      reservations: 10
                      dayInvoincing: 10000
                    - date: '2020-06-04'
                      reservations: 11
                      dayInvoincing: 11000
                    - date: '2020-06-05'
                      reservations: 12
                      dayInvoincing: 12000
                    - date: '2020-06-06'
                      reservations: 13
                      dayInvoincing: 13000
                    - date: '2020-06-07'
                      reservations: 14
                      dayInvoincing: 14000
                    - date: '2020-06-09'
                      reservations: 30
                      dayInvoincing: 15000
                    - date: '2020-06-09'
                      reservations: 30
                      dayInvoincing: 16000
                    - date: '2020-06-10'
                      reservations: 30
                      dayInvoincing: 17000
                    - date: '2020-06-11'
                      reservations: 30
                      dayInvoincing: 18000
                    - date: '2020-06-12'
                      reservations: 30
                      dayInvoincing: 19000
                    - date: '2020-06-13'
                      reservations: 30
                      dayInvoincing: 20000
                    - date: '2020-06-14'
                      reservations: 30
                      dayInvoincing: 20000
                    - date: '2020-06-15'
                      reservations: 30
                      dayInvoincing: 21000
                    - date: '2020-06-16'
                      reservations: 30
                      dayInvoincing: 22000
                    - date: '2020-06-17'
                      reservations: 30
                      dayInvoincing: 23000
                    - date: '2020-06-18'
                      reservations: 30
                      dayInvoincing: 24000
                    - date: '2020-06-19'
                      reservations: 30
                      dayInvoincing: 25000
                    - date: '2020-06-20'
                      reservations: 30
                      dayInvoincing: 26000
                    - date: '2020-06-21'
                      reservations: 30
                      dayInvoincing: 27000
                    - date: '2020-06-22'
                      reservations: 30
                      dayInvoincing: 28000
                    - date: '2020-06-23'
                      reservations: 30
                      dayInvoincing: 29000
                    - date: '2020-06-24'
                      reservations: 30
                      dayInvoincing: 30000
                    - date: '2020-06-25'
                      reservations: 30
                      dayInvoincing: 23000
                    - date: '2020-06-26'
                      reservations: 30
                      dayInvoincing: 24000
                    - date: '2020-06-27'
                      reservations: 30
                      dayInvoincing: 25000
                    - date: '2020-06-28'
                      reservations: 30
                      dayInvoincing: 20000
                    - date: '2020-06-29'
                      reservations: 30
                      dayInvoincing: 21000
                    - date: '2020-06-30'
                      reservations: 30
                      dayInvoincing: 22000
components:
  schemas: {}
